In [2]:
import pandas as pd
import os

# 파일이 있는 디렉토리 경로
directory = "Data/시도별 인구수_1단위"

# 디렉토리 내의 모든 CSV 파일 목록 가져오기
file_list = [f for f in os.listdir(directory) if f.endswith('.csv')]

# 파일 목록을 정렬하여 순서대로 처리
file_list.sort()

# 첫 번째 파일 읽기 (기준 데이터프레임)
base_df = pd.read_csv(os.path.join(directory, file_list[0]), encoding='euc-kr')

# 나머지 파일들을 순차적으로 병합
for file_name in file_list[1:]:
    # 파일 읽기
    file_path = os.path.join(directory, file_name)
    df = pd.read_csv(file_path, encoding='euc-kr')
    
    # 파일명에서 연도와 월 추출
    year_month = file_name[:11].replace('_', '')
    suffix = f"_{year_month}"
    
    # 데이터프레임 병합
    base_df = pd.merge(base_df, df, on='행정구역', how='left', suffixes=('', suffix))

# 결과 확인
print(base_df.head())
print(base_df.columns)

# 결과 저장
base_df.to_csv("병합된_인구데이터_전체_1세별.csv", index=False, encoding='utf-8-sig')

                     행정구역 2020년01월_계_총인구수 2020년01월_계_연령구간인구수 2020년01월_계_0세  \
0     서울특별시  (1100000000)       9,733,509          1,588,081        50,222
1  서울특별시 종로구 (1111000000)         151,215             21,763           620
2   서울특별시 중구 (1114000000)         126,201             15,870           675
3  서울특별시 용산구 (1117000000)         229,385             32,914         1,212
4  서울특별시 성동구 (1120000000)         300,410             46,567         2,038

  2020년01월_계_1세 2020년01월_계_2세 2020년01월_계_3세 2020년01월_계_4세 2020년01월_계_5세  \
0        54,614        58,642        65,019        69,823        69,213
1           584           683           766           874           865
2           670           722           788           791           766
3         1,299         1,307         1,477         1,506         1,454
4         2,114         2,192         2,379         2,332         2,346

  2020년01월_계_6세  ... 2024년04월_여_11세 2024년04월_여_12세 2024년04월_여_13세  \
0        68,649  ...         35,442         34,900         36,011
1           839  ...            455            471            491
2           769  ...            292            291            283
3         1,389  ...            613            598            625
4         2,173  ...            909            834            817

  2024년04월_여_14세 2024년04월_여_15세 2024년04월_여_16세 2024년04월_여_17세 2024년04월_여_18세  \
0         33,609         35,194         37,797         35,915         35,659
1            435            495            525            515            495
2            249            274            350            285            336
3            594            681            683            653            669
4            741            854            935            887            988

  2024년04월_여_19세 2024년04월_여_20세
0         41,236         47,108
1            679            776
2            411            565
3            866            989
4          1,207          1,497

[5 rows x 3589 columns]
Index(['행정구역', '2020년01월_계_총인구수', '2020년01월_계_연령구간인구수', '2020년01월_계_0세',
       '2020년01월_계_1세', '2020년01월_계_2세', '2020년01월_계_3세', '2020년01월_계_4세',
       '2020년01월_계_5세', '2020년01월_계_6세',
       ...
       '2024년04월_여_11세', '2024년04월_여_12세', '2024년04월_여_13세', '2024년04월_여_14세',
       '2024년04월_여_15세', '2024년04월_여_16세', '2024년04월_여_17세', '2024년04월_여_18세',
       '2024년04월_여_19세', '2024년04월_여_20세'],
      dtype='object', length=3589)

In [3]:
base_df.head()

,행정구역,2020년01월_계_총인구수,2020년01월_계_연령구간인구수,2020년01월_계_0세,2020년01월_계_1세,2020년01월_계_2세,2020년01월_계_3세,2020년01월_계_4세,2020년01월_계_5세,2020년01월_계_6세,...,2024년04월_여_11세,2024년04월_여_12세,2024년04월_여_13세,2024년04월_여_14세,2024년04월_여_15세,2024년04월_여_16세,2024년04월_여_17세,2024년04월_여_18세,2024년04월_여_19세,2024년04월_여_20세
0,서울특별시 (1100000000),"9,733,509","1,588,081","50,222","54,614","58,642","65,019","69,823","69,213","68,649",...,"35,442","34,900","36,011","33,609","35,194","37,797","35,915","35,659","41,236","47,108"
1,서울특별시 종로구 (1111000000),"151,215","21,763",620,584,683,766,874,865,839,...,455,471,491,435,495,525,515,495,679,776
2,서울특별시 중구 (1114000000),"126,201","15,870",675,670,722,788,791,766,769,...,292,291,283,249,274,350,285,336,411,565
3,서울특별시 용산구 (1117000000),"229,385","32,914","1,212","1,299","1,307","1,477","1,506","1,454","1,389",...,613,598,625,594,681,683,653,669,866,989
4,서울특별시 성동구 (1120000000),"300,410","46,567","2,038","2,114","2,192","2,379","2,332","2,346","2,173",...,909,834,817,741,854,935,887,988,"1,207","1,497"

In [4]:
base_df.columns

Index(['행정구역', '2020년01월_계_총인구수', '2020년01월_계_연령구간인구수', '2020년01월_계_0세',
       '2020년01월_계_1세', '2020년01월_계_2세', '2020년01월_계_3세', '2020년01월_계_4세',
       '2020년01월_계_5세', '2020년01월_계_6세',
       ...
       '2024년04월_여_11세', '2024년04월_여_12세', '2024년04월_여_13세', '2024년04월_여_14세',
       '2024년04월_여_15세', '2024년04월_여_16세', '2024년04월_여_17세', '2024년04월_여_18세',
       '2024년04월_여_19세', '2024년04월_여_20세'],
      dtype='object', length=3589)