### 일단 읽을수 있는 데이터는 다 읽어보자!

### 아이돌보미 현황부터 확인

In [8]:
import pandas as pd
childCare_Membership_Current = pd.read_excel("데이터파일/여성가족부_아이돌봄 회원현황 정보 서비스_20240611.xlsx")

interview_evaluation = pd.read_excel("데이터파일/여성가족부_아이돌보미 면접 평가 표준 항목_20210817.xlsx")
service_info1 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 서비스별 정보 서비스_20240611.xlsx")
service_info2 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 성별 정보 서비스_20240611.xlsx")
service_info3 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 연령대별 정보 서비스_20240611.xlsx")
service_info4 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 정보 서비스_20240611.xlsx")

In [12]:
service_info1.head()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,서비스총돌보미수,시간제돌보미수,영아종일제돌보미수,종합형돌보미수,질병아동돌보미수,기관연계돌보미수,데이터기준일자
0,202001,C0421,(사)순천YWCA,C0505,전라남도 광역거점,139,135,20,0,10,0,20240611
1,202001,C0383,강원 강릉시 강릉어린이집연합회,C0500,강원도 광역거점,110,100,35,0,12,0,20240611
2,202001,C0384,강원 고성군 건강가정지원센터,C0500,강원도 광역거점,15,15,0,0,0,0,20240611
3,202001,C0385,강원 동해시 건강가정.다문화가족지원센터,C0500,강원도 광역거점,56,56,1,1,5,0,20240611
4,202001,C0387,강원 속초시 가족센터,C0500,강원도 광역거점,51,50,3,4,2,0,20240611

In [5]:
service_info2.tail()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,당월돌보미수,당월남성돌보미수,당월여성돌보미수,누적전체성별돌보미수,누적남성돌보미수,누적여성돌보미수,데이터기준일자
11765,202404,C0268,충북 진천군 가족센터,C0501,충청북도 광역거점,53,0,53,53,0,53,20240611
11766,202404,C0273,충북 청주시 가족센터,C0501,충청북도 광역거점,243,0,243,249,0,249,20240611
11767,202404,C0274,충북 충주시가족센터,C0501,충청북도 광역거점,178,0,178,180,0,180,20240611
11768,202404,C0451,칠곡군가족센터,C0506,경상북도 광역거점,147,0,147,150,0,150,20240611
11769,202404,C0381,하남시 가족센터,C0498,경기도 아이돌봄광역지원센터,224,0,224,232,0,232,20240611

In [7]:
service_info3.tail()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,당월전체연령돌보미수,당월연령0_40돌보미수,당월연령40_45돌보미수,당월연령45_50돌보미수,당월연령50_55돌보미수,...,당월연령65_00돌보미수,누적전체연령돌보미수,누적연령0_40돌보미수,누적연령40_45돌보미수,누적연령45_50돌보미수,누적연령50_55돌보미수,누적연령55_60돌보미수,누적연령60_65돌보미수,누적연령65_00돌보미수,데이터기준일자
11765,202404,C0268,충북 진천군 가족센터,C0501,충청북도 광역거점,53,0,2,1,8,...,4,53,0,2,1,8,23,16,3,20240611
11766,202404,C0273,충북 청주시 가족센터,C0501,충청북도 광역거점,243,0,0,6,37,...,44,249,0,0,7,38,79,81,44,20240611
11767,202404,C0274,충북 충주시가족센터,C0501,충청북도 광역거점,178,0,1,4,40,...,17,180,0,1,4,43,62,56,14,20240611
11768,202404,C0451,칠곡군가족센터,C0506,경상북도 광역거점,147,1,3,9,33,...,11,150,1,3,10,33,44,47,12,20240611
11769,202404,C0381,하남시 가족센터,C0498,경기도 아이돌봄광역지원센터,224,0,1,9,21,...,77,232,1,3,10,21,56,65,76,20240611

In [10]:
service_info3.head()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,당월전체연령돌보미수,당월연령0_40돌보미수,당월연령40_45돌보미수,당월연령45_50돌보미수,당월연령50_55돌보미수,...,당월연령65_00돌보미수,누적전체연령돌보미수,누적연령0_40돌보미수,누적연령40_45돌보미수,누적연령45_50돌보미수,누적연령50_55돌보미수,누적연령55_60돌보미수,누적연령60_65돌보미수,누적연령65_00돌보미수,데이터기준일자
0,202001,C0421,(사)순천YWCA,C0505,전라남도 광역거점,139,0,0,18,31,...,7,139,0,0,18,33,47,34,7,20240611
1,202001,C0383,강원 강릉시 강릉어린이집연합회,C0500,강원도 광역거점,112,0,1,13,24,...,10,110,0,1,13,24,34,28,10,20240611
2,202001,C0384,강원 고성군 건강가정지원센터,C0500,강원도 광역거점,18,0,2,3,1,...,2,15,0,2,2,0,7,2,2,20240611
3,202001,C0385,강원 동해시 건강가정.다문화가족지원센터,C0500,강원도 광역거점,67,0,5,14,12,...,0,56,0,4,13,8,24,7,0,20240611
4,202001,C0387,강원 속초시 가족센터,C0500,강원도 광역거점,56,1,2,4,11,...,2,51,1,0,4,10,23,11,2,20240611

In [11]:
service_info4.head()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,당월돌보미수,당월종합형가능돌보미수,당월자격증소지돌보미수,당월바로연계가능돌보미수,누적자격증소지돌보미수
0,202001,C0421,(사)순천YWCA,C0505,전라남도 광역거점,139,5,18,116,18
1,202001,C0383,강원 강릉시 강릉어린이집연합회,C0500,강원도 광역거점,112,8,10,88,9
2,202001,C0384,강원 고성군 건강가정지원센터,C0500,강원도 광역거점,18,4,1,18,0
3,202001,C0385,강원 동해시 건강가정.다문화가족지원센터,C0500,강원도 광역거점,67,55,8,54,4
4,202001,C0387,강원 속초시 가족센터,C0500,강원도 광역거점,56,32,10,42,9