### 일단 읽을수 있는 데이터는 다 읽어보자!

In [1]:
import pandas as pd
childCare_Membership_Current = pd.read_excel("데이터파일/여성가족부_아이돌봄 회원현황 정보 서비스_20240611.xlsx")
interview_evaluation = pd.read_excel("데이터파일/여성가족부_아이돌보미 면접 평가 표준 항목_20210817.xlsx")
service_info1 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 서비스별 정보 서비스_20240611.xlsx")
service_info2 = pd.read_excel("데이터파일/여성가족부_아이돌보미 현황 성별 정보 서비스_20240611.xlsx")

In [2]:
childCare_Membership_Current.head()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,전체회원수,웹회원수,승인대기회원수,정회원수,정기정회원수,대기정회원수,휴면회원수,신규회원수,신규아동수,데이터기준일자
0,202001,C0421,(사)순천YWCA,C0505,전라남도 광역거점,2719,54,0,2291,337.0,37.0,0,36,116,20240611
1,202001,C0383,강원 강릉시 강릉어린이집연합회,C0500,강원도 광역거점,1692,29,0,1399,264.0,0.0,0,25,68,20240611
2,202001,C0384,강원 고성군 건강가정지원센터,C0500,강원도 광역거점,150,5,0,107,38.0,0.0,0,4,14,20240611
3,202001,C0385,강원 동해시 건강가정.다문화가족지원센터,C0500,강원도 광역거점,729,11,0,600,118.0,0.0,0,9,20,20240611
4,202001,C0387,강원 속초시 가족센터,C0500,강원도 광역거점,787,22,0,653,112.0,0.0,0,12,33,20240611

In [3]:
interview_evaluation.tail()

    기준년도  평가요소(배점)                                                 내용 평가등급  점수
63  2021  적극성(15점)  직업인으로 아이돌보미 활동에 임할 자세가 되어 있는가-소속 기관의 복무 및 업무 지...    D   6
64  2021  적극성(15점)  직업인으로 아이돌보미 활동에 임할 자세가 되어 있는가-소속 기관의 복무 및 업무 지...    E   3
65  2021  적극성(15점)  돌봄 수요 있을 시 적극적으로 활동할 의사가 있는가-심야주말공휴일 활동 가능 여부,...    A  15
66  2021  적극성(15점)  돌봄 수요 있을 시 적극적으로 활동할 의사가 있는가-심야주말공휴일 활동 가능 여부,...    B  12
67  2021  적극성(15점)  돌봄 수요 있을 시 적극적으로 활동할 의사가 있는가-심야주말공휴일 활동 가능 여부,...    C   9

In [4]:
service_info1.tail()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,서비스총돌보미수,시간제돌보미수,영아종일제돌보미수,종합형돌보미수,질병아동돌보미수,기관연계돌보미수,데이터기준일자
11765,202404,C0268,충북 진천군 가족센터,C0501,충청북도 광역거점,53,52,2,0,0,0,20240611
11766,202404,C0273,충북 청주시 가족센터,C0501,충청북도 광역거점,249,247,10,25,20,10,20240611
11767,202404,C0274,충북 충주시가족센터,C0501,충청북도 광역거점,180,177,10,9,2,0,20240611
11768,202404,C0451,칠곡군가족센터,C0506,경상북도 광역거점,150,146,7,16,25,0,20240611
11769,202404,C0381,하남시 가족센터,C0498,경기도 아이돌봄광역지원센터,232,229,19,0,8,0,20240611

In [5]:
service_info2.tail()

,기준연월,아이돌봄기관번호,아이돌봄기관명,상위아이돌봄기관번호,상위아이돌봄기관명,당월돌보미수,당월남성돌보미수,당월여성돌보미수,누적전체성별돌보미수,누적남성돌보미수,누적여성돌보미수,데이터기준일자
11765,202404,C0268,충북 진천군 가족센터,C0501,충청북도 광역거점,53,0,53,53,0,53,20240611
11766,202404,C0273,충북 청주시 가족센터,C0501,충청북도 광역거점,243,0,243,249,0,249,20240611
11767,202404,C0274,충북 충주시가족센터,C0501,충청북도 광역거점,178,0,178,180,0,180,20240611
11768,202404,C0451,칠곡군가족센터,C0506,경상북도 광역거점,147,0,147,150,0,150,20240611
11769,202404,C0381,하남시 가족센터,C0498,경기도 아이돌봄광역지원센터,224,0,224,232,0,232,20240611